name: test
on:
    pull_request:
    push:
        branches:
            - main
        tags:
            - v*
    schedule:
        - cron: "0 * * * *"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 5
    workflow-run-history:
        name: Workflow
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
            - uses: ./
              id: summarizeHistory
              timeout-minutes: 2
            - run: echo "$HISTORY_OUTPUTS"
              env:
                  HISTORY_OUTPUTS: ${{ toJSON(steps.summarizeHistory.outputs) }}
